### PR TITLE
Patch to #15

### PR DESCRIPTION
**Pull request by 0x0elliot**
https://github.com/NullPxl/NullCTF/issues/15 patch to this issue. turned off all everyone, user and role mentions :)

### CODE REVIEW

**Comment by 0x0elliot** [comment]
<a href="https://github.com/NullPxl/NullCTF/issue/15">#15</a>

**Comment by NullPxl** [comment]
Thanks! Looks like this was also possible with many of the encoding/decoding commands (rot, b64, etc.). I'd never noticed because I disabled mentions in permissions when testing the bot.

**Comment by 0x0elliot** [comment]
glad to have helped! kindly also redeploy the original version which can't be added anymore which is still up on big servers

**Comment by NullPxl** [comment]
Of course, should be up now 👍

**Pull request merged**
